### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nbkhope** [zhukmj/sails-graphql#8]

**Comment by TokenChingy** [comment]
Any update on this?

**Comment by nbkhope** [comment]
probably not :)

**Comment by sayjeyhi** [comment]
Is it dead ?!  Any new alternative repo ?

**Comment by zhukmj** [comment]
@jafar-rezaei I created this project just for fun a few years ago :) I honestly forgot about it. If it still can be useful anyone, let me know and I'll try to help you!

**Comment by zhukmj** [comment]
I'm closing this issue as I start supporting this project again. Feel free to open new issues for bug reports or feature requests. Any ideas would be very much appreciated!
